// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int times = Integer.parseInt(args[0]);//gets number of times to run random
		
		int above = 0; //counts times of >0.5
		int below = 0; //counts time of <=0.5

		for(int i = 0; i < times; i++){
			double rNum = Math.random(); //generates a random number
			if(rNum > 0.5) above++;
			else below++;
		}
		System.out.println("> 0.5: " + above + " times");
		System.out.println("<= 0.5: " + below + " times");

		if(above != 0 && below !=0){ //checks if you can calculate ratio 
			System.out.println("Ratio: " + ((double) above/below));
		}

	}
}
